#!/bin/bash

cat << 'EOF'
Content-type: text/html

<!DOCTYPE html>
<html>
<head>
    <title>Bash Language Info</title>
    <style>
        body {
            font-family: Monaco, Consolas, monospace;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background: linear-gradient(135deg, #4d4d4d 0%, #1a1a1a 100%);
            color: #00ff00;
        }
        .container {
            background: rgba(0, 0, 0, 0.8);
            padding: 30px;
            border-radius: 15px;
            border: 2px solid #00ff00;
            box-shadow: 0 0 20px #00ff00;
        }
        .language-header {
            text-align: center;
            margin-bottom: 30px;
            text-shadow: 0 0 10px #00ff00;
        }
        .bash-color { color: #00ff00; }
        .info-box {
            background: rgba(0, 255, 0, 0.1);
            padding: 20px;
            margin: 15px 0;
            border-radius: 10px;
            border-left: 5px solid #00ff00;
        }
        .terminal {
            background: #000;
            padding: 15px;
            border-radius: 5px;
            border: 1px solid #00ff00;
            font-family: monospace;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="language-header">
            <h1 class="bash-color">💻 Bash Language</h1>
            <p><em>This page was generated by Bash CGI</em></p>
        </div>
        
        <div class="info-box">
            <h2>About Bash</h2>
            <p><strong>Bash</strong> (Bourne Again SHell) is a Unix shell and command language.</p>
        </div>
        
        <div class="info-box">
            <h2>History</h2>
            <p>Created by <strong>Brian Fox</strong> in 1989 for the GNU Project.</p>
            <p>Bash is the default shell on most Linux distributions and macOS.</p>
        </div>
        
        <div class="info-box">
            <h2>Key Features</h2>
            <ul>
                <li>Command line interpretation</li>
                <li>Shell scripting for automation</li>
                <li>Pipes and redirection</li>
                <li>Job control and command history</li>
            </ul>
        </div>
        
        <div class="info-box">
            <h2>Server Information</h2>
            <p><strong>Bash Version:</strong> 
EOF

bash --version | head -n1

cat << 'EOF'
            </p>
            <p><strong>Generated:</strong> 
EOF

date

cat << 'EOF'
            </p>
            <p><strong>User:</strong> 
EOF

whoami

cat << 'EOF'
            </p>
        </div>
        
        <div class="terminal">
            <p>$ echo "Hello from Bash CGI"</p>
            <p>Hello from Bash CGI</p>
        </div>
    </div>
</body>
</html>
EOF