#!/usr/bin/perl

print <<'HTML';
<!DOCTYPE html>
<html>
<head>
    <title>Perl Language Info</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            max-width: 800px; 
            margin: 40px auto; 
            padding: 20px;
            background: linear-gradient(135deg, #0098c3 0%, #2e5e95 100%);
            color: white;
        }
        .container {
            background: rgba(255,255,255,0.1);
            padding: 30px;
            border-radius: 15px;
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255,255,255,0.2);
        }
        .language-header {
            text-align: center;
            margin-bottom: 30px;
        }
        .perl-color { color: #8b4513; }
        .info-box { 
            background: rgba(255,255,255,0.15); 
            padding: 20px; 
            margin: 15px 0; 
            border-radius: 10px;
            border-left: 5px solid #8b4513;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="language-header">
            <h1 class="perl-color">🐫 Perl Language</h1>
            <p><em>This page was generated by Perl CGI</em></p>
        </div>
        
        <div class="info-box">
            <h2>About Perl</h2>
            <p><strong>Perl</strong> is a high-level, general-purpose programming language known for its text processing capabilities.</p>
        </div>
        
        <div class="info-box">
            <h2>History</h2>
            <p>Created by <strong>Larry Wall</strong> in 1987.</p>
            <p>Perl stands for "Practical Extraction and Reporting Language".</p>
        </div>
        
        <div class="info-box">
            <h2>Key Features</h2>
            <ul>
                <li>Powerful text processing with regular expressions</li>
                <li>Cross-platform compatibility</li>
                <li>Large collection of modules (CPAN)</li>
                <li>Strong in system administration</li>
            </ul>
        </div>
        
        <div class="info-box">
            <h2>Server Information</h2>
            <p><strong>Perl Version:</strong> 
HTML

print $];

print "</p><p><strong>Generated:</strong> ";

print scalar localtime;

print "</p></div></div></body></html>";