#!/usr/bin/php-cgi

<!DOCTYPE html>
<html>
<head>
    <title>PHP Language Info</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            max-width: 800px; 
            margin: 40px auto; 
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .container {
            background: rgba(255,255,255,0.1);
            padding: 30px;
            border-radius: 15px;
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255,255,255,0.2);
        }
        .language-header {
            text-align: center;
            margin-bottom: 30px;
        }
        .php-color { color: #8892BF; }
        .info-box { 
            background: rgba(255,255,255,0.15); 
            padding: 20px; 
            margin: 15px 0; 
            border-radius: 10px;
            border-left: 5px solid #8892BF;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="language-header">
            <h1 class="php-color">🐘 PHP Language</h1>
            <p><em>This page was generated by PHP CGI</em></p>
        </div>
        
        <div class="info-box">
            <h2>About PHP</h2>
            <p><strong>PHP</strong> (Hypertext Preprocessor) is a server-side scripting language designed for web development.</p>
        </div>
        
        <div class="info-box">
            <h2>History</h2>
            <p>Created by <strong>Rasmus Lerdorf</strong> in 1994. Originally stood for "Personal Home Page" tools.</p>
            <p>PHP 3.0 (1998) was the first version that resembled today's PHP. PHP 7 (2015) brought significant performance improvements.</p>
        </div>
        
        <div class="info-box">
            <h2>Key Features</h2>
            <ul>
                <li>Server-side execution</li>
                <li>Embedded directly in HTML</li>
                <li>Extensive database support</li>
                <li>Large ecosystem (WordPress, Laravel, Symfony)</li>
            </ul>
        </div>
        
        <div class="info-box">
            <h2>Server Information</h2>
            <p><strong>PHP Version:</strong> <?php echo phpversion(); ?></p>
            <p><strong>Generated:</strong> <?php echo date('Y-m-d H:i:s'); ?></p>
            <p><strong>Zend Engine:</strong> <?php echo zend_version(); ?></p>
        </div>
    </div>
</body>
</html>