#!/usr/bin/python3

import datetime
import sys

print("<html>")
print("<head><title>Python Language</title>")
print("<style>")
print("body { font-family: Arial; background: linear-gradient(135deg, #3776ab 0%, #2e5e8f 100%); color: white; margin: 0; padding: 20px; min-height: 100vh; }")
print(".container { max-width: 1000px; margin: 0 auto; }")
print(".box { background: rgba(255,255,255,0.15); padding: 25px; margin: 15px 0; border-radius: 15px; backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.2); }")
print(".python { color: #ffde57; font-weight: bold; text-shadow: 0 0 10px rgba(255,222,87,0.5); }")
print(".header { text-align: center; padding: 30px 0; }")
print(".feature-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin: 20px 0; }")
print(".feature { background: rgba(255,255,255,0.1); padding: 15px; border-radius: 10px; border-left: 4px solid #ffde57; }")
print(".code { background: rgba(0,0,0,0.3); padding: 15px; border-radius: 8px; font-family: 'Courier New', monospace; margin: 15px 0; }")
print(".info-row { display: flex; justify-content: space-between; margin: 10px 0; }")
print(".highlight { color: #ffde57; font-weight: bold; }")
print("</style>")
print("</head>")
print("<body>")

print("<div class='container'>")

print("<div class='header'>")
print("<h1>🐍 This is <span class='python'>Python</span></h1>")
print("<p><em>Powerful, intuitive programming language</em></p>")
print("</div>")

print("<div class='box'>")
print("<h2>📖 About Python</h2>")
print("<p><span class='highlight'>Python</span> is a high-level, interpreted programming language known for its clear syntax and readability.</p>")
print("<p>Created by <span class='highlight'>Guido van Rossum</span> in 1991, it was named after Monty Python's Flying Circus.</p>")
print("<p>Python emphasizes code readability and allows programmers to express concepts in fewer lines of code.</p>")
print("</div>")

print("<div class='box'>")
print("<h2>⭐ Key Features</h2>")
print("<div class='feature-grid'>")
print("<div class='feature'><strong>Easy to Learn</strong><br>Clean syntax, minimal code</div>")
print("<div class='feature'><strong>Versatile</strong><br>Web, AI, data science, automation</div>")
print("<div class='feature'><strong>Large Community</strong><br>Vast library ecosystem</div>")
print("<div class='feature'><strong>Cross-Platform</strong><br>Runs anywhere</div>")
print("</div>")
print("</div>")

print("<div class='box'>")
print("<h2>🚀 Popular Uses</h2>")
print("<div class='info-row'><span>🤖 Artificial Intelligence</span><span>TensorFlow, PyTorch</span></div>")
print("<div class='info-row'><span>📊 Data Science</span><span>Pandas, NumPy, SciPy</span></div>")
print("<div class='info-row'><span>🌐 Web Development</span><span>Django, Flask</span></div>")
print("<div class='info-row'><span>📱 Desktop Apps</span><span>Tkinter, PyQt</span></div>")
print("<div class='info-row'><span>🔧 Automation</span><span>Scripting, DevOps</span></div>")
print("</div>")

print("<div class='box'>")
print("<h2>💻 Example Code</h2>")
print("<div class='code'>")
print("# Simple Python function<br>")
print("def fibonacci(n):<br>")
print("&nbsp;&nbsp;&nbsp;&nbsp;if n <= 1:<br>")
print("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return n<br>")
print("&nbsp;&nbsp;&nbsp;&nbsp;return fibonacci(n-1) + fibonacci(n-2)<br>")
print("<br>")
print("# List comprehension example<br>")
print("squares = [x**2 for x in range(10)]<br>")
print("print(squares)  # [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]")
print("</div>")
print("</div>")

print("<div class='box'>")
print("<h2>🔧 Server Information</h2>")
print("<div class='info-row'><span>Python Version:</span><span class='highlight'>" + sys.version.split()[0] + "</span></div>")
print("<div class='info-row'><span>Generated:</span><span>" + datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') + "</span></div>")
print("</div>")

print("<div class='box'>")
print("<h2>📈 Python Philosophy</h2>")
print("<p><em>Beautiful is better than ugly.<br>")
print("Explicit is better than implicit.<br>")
print("Simple is better than complex.<br>")
print("Complex is better than complicated.</em></p>")
print("<p>— The Zen of Python (PEP 20)</p>")
print("</div>")

print("</div>")
print("</body>")
print("</html>")